import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home = ({ listings }: { listings: any }) => {
  const renderListings = () => {
    return listings.map((item) => (
      <div
        key={item._id}
        className="mb-8
        flex
        flex-col
        w-64
        mx-4
      "
      >
        <div className="relative w-64 h-64  rounded-xl mb-4">
          <Image
            src={item.images.picture_url}
            alt="gg"
            layout="fill"
            className="
             object-cover rounded-xl border"
          />
        </div>
        <div
          className="flex justify-between items-center
        "
        >
          <h1 className=" font-semibold">{item.name.substring(0, 18)}...</h1>
          <p className="font-light">${Math.round(item.price.$numberDecimal)} / night</p>
        </div>
      </div>
    ));
  };
  return (
    <div className="mx-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="
      flex
      flex-col
      justify-center
      items-center
      
      "
      >
        <h1>NextBNB</h1>
        <div
          className="border p-8
          grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4;
        "
        >
          {renderListings()}
        </div>
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/listings');
  const listings = await res.json();
  return { props: { listings } };
}

export default Home;
